<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CandyCornDispatcher" Id="{03d12037-d3d5-4cd3-83ab-3a1138816a86}" SpecialFunc="None">
    <Declaration><![CDATA[(*

short summary
=============
dispather for candy corn

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FINAL CandyCornDispatcher EXTENDS AbstractCandyDispatcher
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="eat" Id="{c5739de3-b1f8-41f3-9d7b-6723ce963c12}">
      <Declaration><![CDATA[(*

short summary
=============
this method dispatches candy corn
to a candy consumer 

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

METHOD eat
VAR_INPUT
	(* consumer who eats the candy *)
	consumer	:REFERENCE TO AbstractCandyConsumer;
	(* candy amount in gram *)
	amount		:CandyAmountInGram;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[RETURN(THIS^.eatCandiesIsImpossible(consumer, amount));
consumer.eatCandyCorn(amount);
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>