<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CandyBarDispatcher" Id="{b840d2a5-f1fc-4272-8751-0d5b4a6efaaf}" SpecialFunc="None">
    <Declaration><![CDATA[(*

short summary
=============
dispather for candy bars

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FINAL CandyBarDispatcher EXTENDS AbstractCandyDispatcher
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="eat" Id="{90fd85d0-01c4-4790-8eb5-ce6ab4260012}">
      <Declaration><![CDATA[(*

short summary
=============
this method dispatches candy bars
to a candy consumer 

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

METHOD eat
VAR_INPUT
	(* consumer who eats the candy *)
	consumer	:REFERENCE TO AbstractCandyConsumer;
	(* candy amount in gram *)
	amount		:CandyAmountInGram;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[RETURN(THIS^.eatCandiesIsImpossible(consumer, amount));
consumer.eatCandyBars(amount);
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>