<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="HardCandyDispatcher" Id="{788de098-7618-4f0b-87cc-4fec20ac5bc0}" SpecialFunc="None">
    <Declaration><![CDATA[(*

short summary
=============
dispather for hard candy

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FINAL HardCandyDispatcher EXTENDS AbstractCandyDispatcher
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="eat" Id="{53e02949-ccfc-4ff1-97c2-9c7f7af5b2fd}">
      <Declaration><![CDATA[(*

short summary
=============
this method dispatches hard candies
to a candy consumer 

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

METHOD eat
VAR_INPUT
	(* consumer who eats the candy *)
	consumer	:REFERENCE TO AbstractCandyConsumer;
	(* candy amount in gram *)
	amount		:CandyAmountInGram;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[RETURN(THIS^.eatCandiesIsImpossible(consumer, amount));
consumer.eatHardCandy(amount);
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>