<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SourCandyDispatcher" Id="{b22051b7-1d57-4104-a5ca-fe624e71e31f}" SpecialFunc="None">
    <Declaration><![CDATA[(*

short summary
=============
dispather for sour candy

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FINAL SourCandyDispatcher EXTENDS AbstractCandyDispatcher
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="eat" Id="{2bc0b2d5-de2a-40de-b181-350e4f916933}">
      <Declaration><![CDATA[(*

short summary
=============
this method dispatches sour candies
to a candy consumer 

legal notes
===========
SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
SPDX-License-Identifier: Apache-2.0
For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

*)

METHOD eat
VAR_INPUT
	(* consumer who eats the candy *)
	consumer	:REFERENCE TO AbstractCandyConsumer;
	(* candy amount in gram *)
	amount		:CandyAmountInGram;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[RETURN(THIS^.eatCandiesIsImpossible(consumer, amount));
consumer.eatSourCandy(amount);
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>